---
.travis.yml:
  extras:
    -
      env: CHECK=build DEPLOY_TO_FORGE=yes
  user: arcaik
  secure: "pQkdqxQik/eI2PR62QYK5fktP7TcAvMw+Ub0koEiKioqJQKVJLbXQZxv3QLK+gPFaPZZz5CMbBEXwRdimYcVkx1QgSsi+wxBt5ZG7bL6LQKOS6TcK9+iwjUuJ9tVFdEedahHni7FftYv08qLKxgsKxQZmq5HzxZ03txu5ve638/gj6kpjseeLrTM32NQP50zI0ibW6iP9oXZFBFVeVrrl86JwLu1DEFCTMhycVL7M0Jm8zXvggTXmKC3m2+Tbld4xImpDSdR6A3N++NYEcxst91uG83K8uupeBpt6e3h3iMi90mJzzJXEuS7M6kt/xCDK7rnekrPGEdRZrN6Mw3XCx6ceOJY3iz9K84DbMgFNIjoXoMbxCA6xj13D6n36PWKRayFkjznyYnDjaUfxbKnyjf4cN30W9Ylt09xwJu65LhdTVQ18EBgwfeo4MBkIqFKkV8G1GMNNmEFH4gg4LmJQ019KscAsNajAl93qdkHvj7z+Vv2lIz0cv2Xk3uTusbgwZxLmXcd7dEofTA09v4SCuJMufQWCqfAubgjqg4l6A9jHUYkOGsUsItH63NuIQJAZJfs0r+CdbgW+FkcRrcgX4gww5c/0ulGPuqVx9nyzsSI43a16PPX+tYSghzXkmMDkPYPZ6zybe0SAF5OXh8xopD1jYNh0OIMmFap8kpydmk="
